apiVersion: v1
kind: Template
labels:
  template: jboss-eap6-elevisor-s2i
  xpaas: 1.0.0
metadata:
  annotations:
    description: Application template for JBOSS applications built with Elevisor using S2I.
    iconClass: icon-jboss
    tags: eap,javaee,java,jboss,xpaas
    version: 1.0.0
    openshift.io/display-name: Red Hat JBoss EAP 6.4 (Elevisor)
  name: jboss-eap6-elevisor
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: jboss-eap6-elevisor-${APPLICATION_NAME}
  spec:
    tags:
    - annotations:
#      openshift.io/imported-from: 192.168.0.153:5000/elevisor/jboss-eap6-openshift-elevisor:latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/jboss-eap-6/eap64-openshift
      generation: 1
      importPolicy:
        insecure: true
      name: latest
      referencePolicy:
        type: Local
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The JBOSS server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${APPLICATION_NAME}

- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap6-elevisor-${APPLICATION_NAME}:latest
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      serviceAccountName: ${SERVICE_ACCOUNT_NAME}
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: ELEVISOR_IG_SERVER_IP
            value: ${ELEVISOR_IG_SERVER_IP}
          - name: ELEVISOR_J2EE_AGENT_NAME
            value: ${ELEVISOR_J2EE_AGENT_NAME}
          - name: ELEVISOR_J2EE_COMMON_PORT
            value: ${ELEVISOR_J2EE_COMMON_PORT}
          - name: ELEVISOR_J2EE_TRACE_PORT
            value: ${ELEVISOR_J2EE_TRACE_PORT}
          - name: ELEVISOR_J2EE_LICENSE
            value: ${ELEVISOR_J2EE_LICENSE}
          - name: ELEVISOR_SYSMON_AGENT_NAME
            value: ${ELEVISOR_SYSMON_AGENT_NAME}
          - name: ELEVISOR_SYSMON_COMMON_PORT
            value: ${ELEVISOR_SYSMON_COMMON_PORT}
          - name: ELEVISOR_SYSMON_LICENSE
            value: ${ELEVISOR_SYSMON_LICENSE}
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8443
            name: ssl
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          livenessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "/opt/eap/bin/livenessProbe.sh"
          readinessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "/opt/eap/bin/readinessProbe.sh"
        terminationGracePeriodSeconds: 60
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: elevisor-app
- displayName: Service Account Name
  description: The name of the service account to use for the deployment.
  name: SERVICE_ACCOUNT_NAME
  value: jboss
  required: true
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
- description: Git source URI for application
  name: SOURCE_REPOSITORY_URL
  required: true
  value: http://elevisor.iptime.org:9937/yeosong.heo/docker-demo.git
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: "master"
- description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
#- description: Git source URI for application
#  name: SOURCE_REPOSITORY_URL
#  required: true
#  value: https://github.com/jboss-openshift/openshift-quickstarts.git
#- description: Git branch/tag reference
#  name: SOURCE_REPOSITORY_REF
#  value: "1.2"
#- description: Path within Git project to build; empty for root project directory.
#  name: CONTEXT_DIR
#  value: tomcat-websocket-chat
- description: GitHub trigger secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
  required: true
- description: Generic build trigger secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
  required: true
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: Elevisor Server IP
  displayName: Elevisor Server IP
  name: ELEVISOR_IG_SERVER_IP
  value : "192.168.0.79"
  required: true
- description: Elevisor Monitoring Project Name
  displayName: Elevisor Monitoring Project Name
  name: ELEVISOR_GROUP_NAME
  value : "SafeKorea"
  required: true
- description: ELEVISOR_J2EE_COMMON_PORT
  displayName: ELEVISOR_J2EE_COMMON_PORT
  name: ELEVISOR_J2EE_COMMON_PORT
  value : "7711"
  required: true
- description: ELEVISOR_J2EE_TRACE_PORT
  displayName: ELEVISOR_J2EE_TRACE_PORT
  name: ELEVISOR_J2EE_TRACE_PORT
  value : "7712"
  required: true
- description: ELEVISOR_J2EE_LICENSE
  displayName: ELEVISOR_J2EE_LICENSE
  name : ELEVISOR_J2EE_LICENSE
  value : "E4B3-ERZA-ERBK-EGD4-ERZA-ERBK-D4UEHRRZC"

- description: ELEVISOR_SYSMON_COMMON_PORT
  displayName: ELEVISOR_SYSMON_COMMON_PORT
  name: ELEVISOR_SYSMON_COMMON_PORT
  value : "7771"
  required: true
- description: ELEVISOR_SYSMON_LICENSE
  displayName: ELEVISOR_SYSMON_LICENSE
  name : ELEVISOR_SYSMON_LICENSE
  value : "TNG4-TF5E-TFGX-EGD9-TF5P-TFGX-D4UEHKF55"
- displayName: Deploy Exploded Archives
  description: Controls whether exploded deployment content should be automatically deployed
  name: AUTO_DEPLOY_EXPLODED
  value: 'false'
  required: false
