#bin/bash
# J2EE
sed "s/%ELEVISOR_IG_SERVER_IP%/${ELEVISOR_IG_SERVER_IP}/g" -i ${ELEVISOR_J2EE_AGENT_HOME}/config/EFJ.conf
sed "s/%ELEVISOR_J2EE_AGENT_NAME%/${ELEVISOR_J2EE_AGENT_NAME}/g" -i ${ELEVISOR_J2EE_AGENT_HOME}/config/EFJ.conf
sed "s/%ELEVISOR_J2EE_COMMON_PORT%/${ELEVISOR_J2EE_COMMON_PORT}/g" -i ${ELEVISOR_J2EE_AGENT_HOME}/config/EFJ.conf
sed "s/%ELEVISOR_J2EE_TRACE_PORT%/${ELEVISOR_J2EE_TRACE_PORT}/g" -i ${ELEVISOR_J2EE_AGENT_HOME}/config/EFJ.conf
sed "s/%ELEVISOR_J2EE_LICENSE%/${ELEVISOR_J2EE_LICENSE}/g" -i ${ELEVISOR_J2EE_AGENT_HOME}/config/EFJ.conf

### SYSMON
sed "s/%ELEVISOR_IG_SERVER_IP%/${ELEVISOR_IG_SERVER_IP}/g" -i ${ELEVISOR_SYSMON_AGENT_HOME}/config/sysmon.conf
sed "s/%ELEVISOR_SYSMON_AGENT_NAME%/${ELEVISOR_SYSMON_AGENT_NAME}/g" -i ${ELEVISOR_SYSMON_AGENT_HOME}/config/sysmon.conf
sed "s/%ELEVISOR_SYSMON_COMMON_PORT%/${ELEVISOR_SYSMON_COMMON_PORT}/g" -i ${ELEVISOR_SYSMON_AGENT_HOME}/config/sysmon.conf
sed "s/%ELEVISOR_SYSMON_LICENSE%/${ELEVISOR_SYSMON_LICENSE}/g" -i ${ELEVISOR_SYSMON_AGENT_HOME}/config/sysmon.conf

